### ISSUE TITLE
Reverse scan for removals/deletions

### ISSUE THREAD

**Issue by bbenning** [emicklei/gmig#41]
It might be preferential when resources are deleted to afterwards remove both the creation and deletion script or maybe flag them or something, to be excluded when setting up a new environment.

**Comment by emicklei** [comment]
that is quite a challenge as it involves interpreting the scripts in each migration.

because the current state is represented by the last migration filename only, older files can be renamed but also removed without affecting infrastructure.

do you have other suggestions to achieve this?
